spring:
  messages:
    basename: messages
  h2:
    console:
      enabled: true # H2 ?? ???
      settings:
        web-allow-others: true # ?? ??? ?? ??
  datasource:
    url: jdbc:h2:mem:testdb # H2 ???? ?????? URL
    username: sa # ??? ??
    password:  # ???? (??? ??)
  jpa:
    hibernate:
      ddl-auto: create-drop # ?????? ?? ? ??????? ???? ?? ??
    show-sql: true # ???? SQL ?? ?? ??
    defer-datasource-initialization: true # ????? ???? ????